Repository surfstudio/iOS-Utils, pull requests merged in 2018-09, with the labels that each got.

#5 Jailbreak detect method
  Surf-Utils.podspec
  Utils/Utils/JailbreakDetect/JailbreakDetect.swift
Labels: Update

#7 bugfix for detect derictories
  Surf-Utils.podspec
  Utils/Utils/JailbreakDetect/JailbreakDetect.swift
Labels: Bugfix

#8 added VibrationFeedbackManager to Utils
  README.md
  Surf-Utils.podspec
  Utils/Utils.xcodeproj/project.pbxproj
  Utils/Utils/VibrationFeedbackManager/UIDevice+feedbackType.swift
  Utils/Utils/VibrationFeedbackManager/UIDevice+hasHapticFeedback.swift
  Utils/Utils/VibrationFeedbackManager/UIDevice+hasTapticEngine.swift
  Utils/Utils/VibrationFeedbackManager/VibrationFeedbackManager.swift
Labels: New
