Repository surfstudio/iOS-Utils, pull requests merged in 2019-11, with the labels that each got.

#40 #35 rename jail break detector
  README.md
  SurfUtils.podspec
  Utils/Utils.xcodeproj/project.pbxproj
  Utils/Utils/BrightSide/BrightSide.swift
Labels: Update

#41 Common button и UIImageExtensions
  README.md
  SurfUtils.podspec
  Utils/Utils.xcodeproj/project.pbxproj
  Utils/Utils/CommonButton/CommonButton.swift
  Utils/Utils/UIImage/UIImageExtensions.swift
Labels: New

#42 Update pod spec for brightside
  SurfUtils.podspec
Labels: bug

#23 LocalStorage
  README.md
  SurfUtils.podspec
  Utils/Utils.xcodeproj/project.pbxproj
  Utils/Utils/CommonButton/CommonButton.swift
  Utils/Utils/LocalStorage/LocalStorage.swift
  Utils/UtilsTests/LocalStorageTests.swift
Labels: New

#47 Geolocation service
  README.md
  SurfUtils.podspec
  Utils/Utils.xcodeproj/project.pbxproj
  Utils/Utils/GeolocationService/GeolocationService.swift
  Utils/Utils/GeolocationService/GeolocationServiceInterface.swift
  Utils/Utils/GeolocationService/Support/GeolocationAccuracy.swift
  Utils/Utils/GeolocationService/Support/GeolocationAuthResult.swift
  Utils/Utils/GeolocationService/Support/GeolocationResult.swift
  Utils/Utils/GeolocationService/Support/LocationManagerInterface.swift
  Utils/UtilsTests/GeolocationServiceTests.swift
Labels: New
